spring:
  webflux:
    base-path: /auths
  application:
    name: auth
  data:
    redis:
      repositories:
        enabled: false

server:
  port: 8010

redis:
  host: redis

jwt:
  issuer: ${JWT_ISSUER}
  secret-key: ${JWT_SECRET}

external-service-url:
  member: "http://member:8020/members"

resilience4j:
  circuitbreaker:
    instances:
      member-service:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        ignore-exceptions:
          - shop.tsrecipe.auth.exception.BaseException

app-platform-properties:
  platform:
    android:
      google: ${ANDROID_CLIENT_ID_GOOGLE}
      apple: ${ANDROID_CLIENT_ID_APPLE}
    ios:
      google: ${IOS_CLIENT_ID_GOOGLE}
      apple: ${IOS_CLIENT_ID_APPLE}

oauth-properties:
  provider:
    google:
      jwks-uri: "https://www.googleapis.com/oauth2/v3/certs"
      issuer: "https://accounts.google.com"
    apple:
      jwks-uri: "https://appleid.apple.com/auth/keys"
      issuer: "https://appleid.apple.com"

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: /v3/api-docs

logging:
  level:
    org.springframework.web: DEBUG
