apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  SPRING_PROFILES_ACTIVE: "__PROFILE__"
  JWT_ISSUER: "__JWT_ISSUER__"
  JWT_SECRET: "__JWT_SECRET__"
  ANDROID_CLIENT_ID_GOOGLE: "__ANDROID_CLIENT_ID_GOOGLE__"
  ANDROID_CLIENT_ID_APPLE: "__ANDROID_CLIENT_ID_APPLE__"
  IOS_CLIENT_ID_GOOGLE: "__IOS_CLIENT_ID_GOOGLE__"
  IOS_CLIENT_ID_APPLE: "__IOS_CLIENT_ID_APPLE__"